### ISSUE TITLE
CryptoTokenKit support?

### ISSUE THREAD

**Issue by stv0g** [ElMostafaIdrassi/goMutualAuthServer#1]
Hi @ElMostafaIdrassi,

your README mentions support for CryptoTokenKit certs. Is this really supported?
How can I specify which token should be used?

**Comment by ElMostafaIdrassi** [comment]
Hi @stv0g

Yes, CryptoTokenKit is supported since it integrates with the Keychain.
Specifying which token to be used is out of the scope of this project as this is just a server. It is up to the client to handle listing tokens and certificates.
Usually, people use browsers to test mutual authentication, and AFAIK, neither Safari nor Chrome/Firefox allow for selecting a specific token. Once you insert your CryptoTokenKit compatible token, and after you visit https://localhost, you should get a popup showing a list of all the TLS certificates that are available in the Keychain, including any that are available via CryptoTokenKit.
